[package]
name = "backend"
version = "0.1.0"
edition = "2021"
default-run = "backend"

[[bin]]
name = "backend"
path = "src/main.rs"

[[bin]]
name = "debug"
path = "src/debug.rs"
test = false

[dependencies]
actix-web = {version = "4.2.1", features = ["rustls"]}
