[tasks.build]
command = "wsl"
args = ["-d", "Ubuntu", "-u", "marunix", "cargo", "build", "--release", "--target=aarch64-unknown-linux-gnu"]

[tasks.stop-server]
command = "ssh"
args = ["-t", "marius@pi.local", "sudo", "systemctl", "stop", "bosler.it-server"]

[tasks.start-server]
command = "ssh"
args = ["-t", "marius@pi.local", "sudo", "systemctl", "start", "bosler.it-server"]

[tasks.restart-server]
command = "ssh"
args = ["-t", "marius@pi.local", "sudo", "systemctl", "restart", "bosler.it-server"]

[tasks.copyToServer]
command = "scp"
args = ["-r", "./target/aarch64-unknown-linux-gnu/release/backend", "marius@pi.local:~/server/bosler.it/backend/"]
dependencies = ["stop-server"]

[tasks.changePermission]
command = "ssh"
args = ["marius@pi.local", "chmod +x -R ~/server/bosler.it/backend"]

[tasks.buildcopy]
dependencies = ["build", "copyToServer", "changePermission"]

[tasks.buildrun]
command = "echo"
args = ["executed buildrun..."]
dependencies = ["build", "copyToServer", "changePermission", "start-server"]
